### ISSUE TITLE
Summary: Needs Improvement

### ISSUE THREAD

**Issue by melissamcewen** [sche159/prj-rev-bwfs-dasmoto#1]
Hi I'm reviewing for codecademy! Great job getting started on this project. With a few tweaks we can get it matching the spec.

Your CSS is really well organized and your HTML uses elements correctly. I'll open some "issues" with tips that will help you get to 100%

I hope you enjoyed building this and are excited to work on it more, as well as to continue the course since once you've got those issues closed you're definitely ready.

**Comment by sche159** [comment]
Sounds good, thank you Melissa!
