### ISSUE TITLE
Spec tools

### ISSUE THREAD

**Issue by melissamcewen** [sche159/prj-rev-bwfs-dasmoto#2]
So what I do is download the spec 
![hello_css___codecademy](https://user-images.githubusercontent.com/1251094/39099505-c634bd58-4641-11e8-96fe-59080c7e1402.png)

Then I use an application that allows me to overlay the spec on the site I'm working on. Lately I've been using Perfect Pixel, which is free for Chrome
https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi?hl=en

![dasmoto_s_arts___crafts_and_unbreaking_technical_interviews_ __puppybits_ _medium](https://user-images.githubusercontent.com/1251094/39099517-fa0d4fbe-4641-11e8-89f7-a81f09ae764f.png)

Pretty neat huh?

Then my next tool is Chrome Inspector https://www.codecademy.com/programs/bd3bff8ce8ce2f11781cdf436a004629/items/73ce848773660b8f73086a073113c3fe

I can highlight elements and then see if they match the spec.

So here it's showing me this text is 48 px when the spec asks for 32px, I'll tell you how that happened in my next issue:
![dasmotos-arts_redline_jpg_and_dasmoto_s_arts___crafts](https://user-images.githubusercontent.com/1251094/39099536-41b09a7e-4642-11e8-94a9-8c5b095e5ddb.png)

**Comment by sche159** [comment]
Cool, thanks for the tips!
